//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkimizda
    {
        public int personel_id { get; set; }
        public string personel_isim { get; set; }
        public string personel_gorev { get; set; }
        public string personel_aciklama { get; set; }
        public string resim { get; set; }
    }
}
