//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int iletisim_id { get; set; }
        public string iletisim_ad { get; set; }
        public string iletisim_email { get; set; }
        public string iletisim_mesaj { get; set; }
    }
}
