//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ozellikler
    {
        public int ozellikler_id { get; set; }
        public string ozellikler_icon { get; set; }
        public string ozellikler_aciklama { get; set; }
        public string ozellikler_butonrenk { get; set; }
    }
}
