//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarihce
    {
        public int tarihce_id { get; set; }
        public string tarihce_baslik { get; set; }
        public string tarihce_aciklama { get; set; }
        public string tarihce_resim { get; set; }
    }
}
